CREATE TABLE IF NOT EXISTS `wp_logistics` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`last_time`  char(19) NOT NULL  COMMENT '物流最后更新时间',
`type`  varchar(100) NOT NULL  COMMENT '快递公司',
`last_state`  int(1) NOT NULL  DEFAULT 0 COMMENT '物流最新状态',
`order_id`  int(32) NOT NULL  COMMENT '单号ID',
`postid`  varchar(255) NOT NULL  COMMENT '快递单号',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_logistics` (`id`,`type`,`last_time`,`last_state`,`order_id`,`postid`) VALUES ('23','shunfeng','','0','970','123');
INSERT INTO `wp_logistics` (`id`,`type`,`last_time`,`last_state`,`order_id`,`postid`) VALUES ('24','shunfeng','','0','966','15655');
INSERT INTO `wp_logistics` (`id`,`type`,`last_time`,`last_state`,`order_id`,`postid`) VALUES ('22','yuantong','2015-09-05 14:37:33','0','968','100459047395');
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('logistics','物流','0','','1','{"1":["type","postid"]}','1:基础','','','','','order_id:订单ID\r\nname:收件人\r\npostid:快递单号\r\ntype|get_name_by_status:快递公司\r\nlast_time:更新时间\r\nlast_state|get_name_by_status:状态\r\nid:操作:[EDIT]|编辑,[DELETE]|删除,more&id=[id]|详情','10','','','1439190551','1441794089','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('last_time','物流最后更新时间','char(19) NOT NULL','string','','','3','','0','0','1','1439277451','1439191158','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('type','快递公司','varchar(100) NOT NULL','select','','','1','shunfeng:顺丰速运\r\nyunda:韵达快运\r\nyuantong:圆通速递\r\nshentong:申通快递\r\nzhongtong:中通速递\r\nhuitongkuaidi:汇通快运\r\nrufengda:如风达\r\nems:EMS快递\r\nzhongtiekuaiyun:中铁快运\r\nups:UPS快运\r\ndhl:DHL快运\r\nzhaijisong:宅急送\r\ntiantian:天天快递\r\nyouzhengguonei:邮政国内小包\r\naae:AAE全球专递\r\nanjie:安捷快递\r\nanxindakuaixi:安信达快递\r\nbiaojikuaidi:彪记快递\r\nbht:BHT\r\nbaifudongfang:百福东方国际物流\r\ncces:希伊艾斯快递\r\ncoe:中国东方（COE）\r\nchangyuwuliu:长宇物流\r\ndatianwuliu:大田物流\r\ndebangwuliu:德邦物流\r\ndpex:DPEX\r\ndsukuaidi:d速快递\r\ndisifang:递四方\r\nfedex:FEDEX（国外）\r\nfeikangda:飞康达物流\r\nfenghuangkuaidi:凤凰快递\r\nfeikuaida:飞快达\r\nnengda:港中能达物流\r\nguangdongyouzhengwuliu:广东邮政物流\r\ngongsuda:共速达\r\nguotongkuaidi:恒路物流\r\nhengluwuliu:华夏龙物流\r\nhuaxialongwuliu:海红\r\nhaihongwangsong:海外环球\r\njiayiwuliu:佳怡物流\r\njinguangsudikuaijian:京广速递\r\njixianda:急先达\r\njjwl:佳吉物流\r\njymwl:加运美物流\r\njindawuliu:金大物流\r\njialidatong:嘉里大通\r\njykd:晋越快递\r\nkuaijiesudi:快捷速递\r\nlianb:联邦快递（国内）\r\nlianhaowuliu:联昊通物流\r\nlongbanwuliu:龙邦物流\r\nlijisong:立即送\r\nlejiedi:乐捷递\r\nminghangkuaidi:民航快递\r\nmeiguokuaidi:美国快递\r\nmenduimen:门对门\r\nocs:OCS\r\npeisihuoyunkuaidi:配思货运\r\nquanchenkuaidi:全晨快递\r\nqfkd:全峰快递\r\nquanjitong:全际通物流\r\nquanritongkuaidi:全日通快递\r\nquanyikuaidi:全一快递\r\nsantaisudi:三态速递\r\nshenghuiwuliu:盛辉物流\r\nsuer:速尔物流\r\nshengfeng:盛丰物流\r\nsaiaodi:赛澳递\r\ntiandihuayu:天地华宇\r\ntnt:TNT\r\nwanjiawuliu:万家物流\r\nwenjiesudi:文捷航空速递\r\nwuyuan:伍圆\r\nwxwl:万象物流\r\nxinbangwuliu:新邦物流\r\nxinfengwuliu:信丰物流\r\nxingchenjibian:星晨急便\r\nyafengsudi:亚风速递\r\nyibangwuliu:一邦速递\r\nyoushuwuliu:优速物流\r\nyouzhengguoji:邮政国际包裹挂号信\r\nyuanchengwuliu:远成物流\r\nyuanweifeng:源伟丰快递\r\nyuanzhijiecheng:元智捷诚快递\r\nyuntongkuaidi:运通快递\r\nyuefengwuliu:越丰物流\r\nyuananda:源安达\r\nyinjiesudi:银捷速递\r\nzhongyouwuliu:中邮物流\r\nzhongxinda:忠信达\r\nzhimakaimen:芝麻开门\r\nguotongkuaidi:国通快递\r\n','0','1','1','1439275331','1439190987','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('last_state','物流最新状态','int(1) NOT NULL','select','0','','3','0:在途，即货物处于运输过程中；\r\n1:揽件，货物已由快递公司揽收并且产生了第一条跟踪信息；\r\n2:疑难，货物寄送过程出了问题；\r\n3:签收，收件人已签收；\r\n4:退签，即货物由于用户拒签、超区等原因退回，而且发件人已经签收；\r\n5:派件，即快递正在进行同城派件；\r\n6:退回，货物正处于退回发件人的途中；','0','0','1','1439276270','1439191386','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('order_id','单号ID','int(32) NOT NULL','cascade','','','2','','0','1','1','1439286091','1439191569','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('postid','快递单号','varchar(255) NOT NULL','string','','','1','','0','1','1','1439277490','1439192154','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;