CREATE TABLE IF NOT EXISTS `wp_red_paper` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`return_msg`  varchar(255) NOT NULL  COMMENT '状态',
`re_openid`  varchar(255) NOT NULL  COMMENT '发放对象',
`total_amount`  int(10) NOT NULL  COMMENT '金额（分）',
`token`  varchar(255) NOT NULL  COMMENT 'Token',
`send_time`  int(10) NOT NULL  COMMENT '发放时间',
`act_name`  varchar(255) NOT NULL  COMMENT '活动名称',
`wishing`  varchar(255) NOT NULL  COMMENT '祝福语',
`remark`  varchar(255) NOT NULL  COMMENT '备注',
`mid`  int(10) NOT NULL  COMMENT '发放用户id',
`mch_billno`  varchar(255) NOT NULL  COMMENT '商户单号',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('red_paper','红包','0','','1','{"1":["re_openid","total_amount","act_name","wishing","remark"]}','1:基础','','','','','id:ID\r\nmch_billno:商户单号\r\nre_openid:收款openid\r\nwx_nickname:微信昵称\r\nheadimgurl:头像\r\nnickname:微分销昵称\r\ntotal_amount:金额（分）\r\nsend_time|time_format:发放时间\r\nremark:备注\r\nmid:发放用户\r\nreturn_msg:状态\r\nid:操作:[EDIT]|编辑,[DELETE]|删除','10','','','1447376499','1447401345','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('return_msg','状态','varchar(255) NOT NULL','string','','','3','','0','0','1','1447396459','1447395664','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('re_openid','发放对象','varchar(255) NOT NULL','string','','','1','','0','0','1','1447376704','1447376704','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('total_amount','金额（分）','int(10) NOT NULL','num','','','1','','0','0','1','1447376733','1447376733','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','Token','varchar(255) NOT NULL','string','','','0','','0','0','1','1447385510','1447376803','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('send_time','发放时间','int(10) NOT NULL','datetime','','','3','','0','0','1','1447398868','1447376856','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('act_name','活动名称','varchar(255) NOT NULL','string','','','1','','0','0','1','1447385824','1447376887','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('wishing','祝福语','varchar(255) NOT NULL','string','','','1','','0','0','1','1447385835','1447376944','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('remark','备注','varchar(255) NOT NULL','textarea','','','1','','0','0','1','1447385587','1447376964','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('mid','发放用户id','int(10) NOT NULL','num','','','0','','0','0','1','1447385519','1447377021','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('mch_billno','商户单号','varchar(255) NOT NULL','string','','','3','','0','0','1','1447394898','1447376604','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;