CREATE TABLE IF NOT EXISTS `wp_shop_comments` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`gid`  int(10) NOT NULL  COMMENT '商品id',
`comments`  text NOT NULL  COMMENT '评论内容',
`token`  varchar(255) NOT NULL  COMMENT 'token',
`ctime`  int(10) NOT NULL  COMMENT '时间',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('shop_comments','商品评价','0','','1','','1:基础','','','','','','10','','','1438246940','1438246940','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('gid','商品id','int(10) NOT NULL','num','','商品id','1','','0','0','1','1438251563','1438247021','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('comments','评论内容','text NOT NULL','textarea','','评论','1','','0','0','1','1438247061','1438247061','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','token','varchar(255) NOT NULL','string','','','1','','0','0','1','1438248787','1438248737','','3','','regex','get_token','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ctime','时间','int(10) NOT NULL','datetime','','评论的时间','1','','0','0','1','1438248818','1438248818','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;

CREATE TABLE IF NOT EXISTS `wp_shop_footer` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`url`  varchar(255) NULL   COMMENT '关联URL',
`title`  varchar(50) NOT NULL  COMMENT '菜单名',
`pid`  tinyint(2) NULL  DEFAULT 0 COMMENT '一级菜单',
`sort`  tinyint(4) NULL   DEFAULT 0 COMMENT '排序号',
`token`  varchar(255) NOT NULL  COMMENT 'Token',
`icon`  int(10) unsigned NULL   COMMENT '图标',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_shop_footer` (`id`,`url`,`title`,`pid`,`sort`,`token`,`icon`) VALUES ('21','{site_url}/index.php?s=/addon/Shop/Shop/index/token/gh_b6ff5c2aaf62.html','首页','0','0','gh_b6ff5c2aaf62','0');
INSERT INTO `wp_shop_footer` (`id`,`url`,`title`,`pid`,`sort`,`token`,`icon`) VALUES ('22','{site_url}/index.php?s=/addon/Shop/Shop/products/token/gh_b6ff5c2aaf62.html','购物车','0','0','gh_b6ff5c2aaf62','0');
INSERT INTO `wp_shop_footer` (`id`,`url`,`title`,`pid`,`sort`,`token`,`icon`) VALUES ('23','{site_url}/index.php?s=/addon/Shop/User/info.html','我','0','0','gh_b6ff5c2aaf62','0');
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('shop_footer','底部导航','0','','1','{"1":["pid","title","url","sort"]}','1:基础','','','','','title:菜单名\r\nicon:图标\r\nurl:关联URL\r\nsort:排序号\r\nid:操作:[EDIT]|编辑,[DELETE]|删除','10','title','','1394518309','1396507698','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('url','关联URL','varchar(255) NULL ','string','','可用{site_url}代表当前网站根地址','1','','0','0','1','1399083504','1394519090','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('title','菜单名','varchar(50) NOT NULL','string','','可创建最多 3 个一级菜单，每个一级菜单下可创建最多 5 个二级菜单。编辑中的菜单不会马上被用户看到，请放心调试。','1','','0','0','1','1394519941','1394518988','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('pid','一级菜单','tinyint(2) NULL','select','0','如果是一级菜单，选择“无”即可','1','0:无','0','0','1','1394519296','1394518930','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('sort','排序号','tinyint(4) NULL ','num','0','数值越小越靠前','1','','0','0','1','1394523288','1394519175','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','Token','varchar(255) NOT NULL','string','','','0','','0','0','1','1394526820','1394526820','','3','','regex','get_token','1','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('icon','图标','int(10) unsigned NULL ','picture','','根据选择的底部模板决定是否需要上传图标','1','','0','0','1','1396506297','1396506297','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;

CREATE TABLE IF NOT EXISTS `wp_shop_distribute` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`manager_openid`  varchar(255) NOT NULL  COMMENT '一级分销',
`seller_openid`  varchar(255) NOT NULL  COMMENT '二级分销',
`openid`  varchar(255) NOT NULL  COMMENT '任何用户的openid',
`token`  varchar(255) NOT NULL  COMMENT 'token',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_shop_distribute` (`id`,`manager_openid`,`seller_openid`,`openid`,`token`) VALUES ('4','osALzjvsweDff9UGcO13UWf2uYbw','','osALzjvsweDff9UGcO13UWf2uYbw','');
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('shop_distribute','商城分销','0','','1','{"1":["first_dis","second_dis","third_dis","openid","dis_sta"]}','1:基础','','','','','id:分销id\r\nopenid:分销姓名\r\ndis_sta|get_name_by_status:类别\r\nfirst_dis:一级分销商\r\nsecond_dis:二级分销商\r\nthird_dis:三级分销商','10','','','1438673403','1438749646','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('manager_openid','一级分销','varchar(255) NOT NULL','string','','','1','','0','0','1','1438909982','1438673441','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('seller_openid','二级分销','varchar(255) NOT NULL','string','','二级分销','1','','0','0','1','1438909996','1438673473','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('openid','任何用户的openid','varchar(255) NOT NULL','string','','openid','1','','0','0','1','1438910032','1438673562','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','token','varchar(255) NOT NULL','string','','token','1','','0','0','1','1438910217','1438910217','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;

CREATE TABLE IF NOT EXISTS `wp_shop_order` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`title`  varchar(255) NOT NULL  COMMENT '商品名称',
`count`  int(10) NOT NULL  COMMENT '商品数量',
`fid`  int(10) NOT NULL  COMMENT '订单的fid',
`userinfo`  text NOT NULL  COMMENT '收件人信息',
`order_status`  char(50) NOT NULL  COMMENT '订单状态',
`timestamp`  int(10) NOT NULL  COMMENT '下单时间',
`user_id`  int(10) NOT NULL  COMMENT '用户id',
`ip`  varchar(255) NOT NULL  COMMENT '支付ip',
`total_fee`  int(10) NOT NULL  COMMENT '总费用',
`product_field`  text NOT NULL  COMMENT '商品',
`unit_price`  int(10) NOT NULL  COMMENT '单价',
`pid`  int(10) NOT NULL  COMMENT '商品id',
`settle_status`  int(50) NOT NULL  DEFAULT 0 COMMENT '分销结算状态',
`by_from_openid`  varchar(255) NOT NULL  COMMENT '购买的上线openid',
`receiver`  varchar(255) NOT NULL  COMMENT '收件人',
`address`  varchar(255) NOT NULL  COMMENT '收件人地址',
`phone`  varchar(255) NOT NULL  COMMENT '联系电弧',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_shop_order` (`id`,`user_id`,`product_field`,`total_fee`,`ip`,`timestamp`,`order_status`,`userinfo`,`fid`,`count`,`title`,`unit_price`,`pid`,`settle_status`,`by_from_openid`,`receiver`,`address`,`phone`) VALUES ('16','2','{"id":"24","title":"\u6c34\u679c","intro":"\u6d4b\u8bd5","mTime":"1437522641","cover":"375","content":"","cTime":"1437522641","token":"gh_b6ff5c2aaf62","param":"<p>\u70ed\u95002<br\/><\/p>","ad_url":"","buy_url":"","cate_id_1":"40","cate_id_2":"0","market_price":"200","discount_price":"50","view_count":"0","img_1":"376","img_2":"370","img_3":"368","img_4":"377","img_5":"367","cate_id":"40","bug_count":"0","stock_price":"0","first_deduct":"0","second_deduct":"0","third_deduct":"0","count":"2","total_fee":100,"unit_price":"50","pid":24}','100','192.168.1.105','1438704000','7','{"openid":-1,"nickname":"\u5c0f\u5b59","phone":"400-3445-222","address":"\u6d59\u6c5f","ctime":"2015-08-05 21:30:05"}','0','2','水果','50','0','1','','','','');
INSERT INTO `wp_shop_order` (`id`,`user_id`,`product_field`,`total_fee`,`ip`,`timestamp`,`order_status`,`userinfo`,`fid`,`count`,`title`,`unit_price`,`pid`,`settle_status`,`by_from_openid`,`receiver`,`address`,`phone`) VALUES ('15','2','{"id":"23","title":"\u6c34\u679c","intro":"\u70ed\u9500\u7684\u6c34\u679c","mTime":"1437522596","cover":"369","content":"","cTime":"1437522596","token":"gh_b6ff5c2aaf62","param":"<p>\u53c2\u65702<br\/><\/p>","ad_url":"","buy_url":"","cate_id_1":"40","cate_id_2":"0","market_price":"100","discount_price":"50","view_count":"0","img_1":"369","img_2":"375","img_3":"372","img_4":"0","img_5":"0","cate_id":"40","bug_count":"0","stock_price":"0","first_deduct":"0","second_deduct":"0","third_deduct":"0","count":1,"total_fee":50,"unit_price":"50","pid":23}','50','192.168.1.105','1438704000','7','{"openid":-1,"nickname":"\u5c0f\u82ac","phone":"1102233344","address":"\u5b89\u5fbd\u7701","ctime":"2015-08-05 21:26:35"}','0','1','水果','50','0','1','','','','');
INSERT INTO `wp_shop_order` (`id`,`user_id`,`product_field`,`total_fee`,`ip`,`timestamp`,`order_status`,`userinfo`,`fid`,`count`,`title`,`unit_price`,`pid`,`settle_status`,`by_from_openid`,`receiver`,`address`,`phone`) VALUES ('17','1','{"id":"22","title":"\u9f99\u5ca9","intro":"\u4e00\u7ea7\u9f99\u5ca9\uff0c\u7f8e\u5bb9\u517b\u989c\uff0c\u8865\u8840\u76ca\u6c14\uff0c\u6297\u8f90\u5c04\u8870\u8001","mTime":"1437105646","cover":"369","content":"","cTime":"1437105646","token":"gh_b6ff5c2aaf62","param":"<p>\u86cb\u767d\u8d28\u662f\u7ef4\u6301\u68c9\u8863\u6280\u80fd\u6700\u91cd\u8981\u7684\u8425\u517b\u7d20\uff0c\u4e3a\u6784\u6210\u767d\u8840\u7403\u548c\u6297\u4f53\u7684\u4e3b\u8981\u6210\u5206\u3002<br\/><\/p>","ad_url":"","buy_url":"","cate_id_1":"40","cate_id_2":"0","market_price":"1","discount_price":"45","view_count":"0","img_1":"369","img_2":"375","img_3":"372","img_4":"376","img_5":"370","cate_id":"40","bug_count":"0","stock_price":"0","back_credit":"0","back_deduct":"","stock":"0","count":1,"total_fee":45,"unit_price":"45","phone":"1234567","address":"\u4e0a\u6d77\u5e02","receiver":"\u674e\u6653\u660e","pid":22,"by_from_openid":"osALzjvsweDff9UGcO13UWf2uYbw"}','45','192.168.1.105','1438876800','5','{"openid":"osALzjvsweDff9UGcO13UWf2uYbw","nickname":"\u674e\u6653\u660e","phone":"1234567","address":"\u4e0a\u6d77\u5e02","ctime":"2015-08-07 15:25:28"}','0','1','龙岩','45','22','0','osALzjvsweDff9UGcO13UWf2uYbw','李晓明','上海市','1234567');
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('shop_order','微商店订单','0','','1','{"1":["order_status","timestamp","user_id","ip","total_fee","userinfo","title","count","fid","unit_price","pid","settle_status","receiver","address","phone"]}','1:基础','','','','','id:ID\r\ntitle:商品名称\r\nip:支付ip\r\ntotal_fee:总费用\r\ntimestamp:下单时间\r\nreceiver:收件人\r\nphone:电话\r\naddress:收件地址\r\norder_status|get_name_by_status:订单状态\r\nsettle_status|get_name_by_status:分销结算状态\r\nid:操作:[EDIT]|编辑','10','title','title','1437698180','1438912241','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('title','商品名称','varchar(255) NOT NULL','string','','商品名称','1','','0','0','1','1437895825','1437895825','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('count','商品数量','int(10) NOT NULL','num','','商品数量','1','','0','0','1','1437831288','1437831288','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('fid','订单的fid','int(10) NOT NULL','num','','订单的父id','1','','0','0','1','1437831058','1437831058','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('userinfo','收件人信息','text NOT NULL','textarea','','收件人信息','1','','0','0','1','1437725908','1437725908','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('order_status','订单状态','char(50) NOT NULL','select','','订单状态1.inorder,2.paied,3.returnGoods,4.agreereturn,','1','1:已下单，未付款\r\n2:已付款，未发货\r\n3:已经发货\r\n4:取消订单\r\n5:申请退货\r\n6:同意退货\r\n7:已确认收货\r\n8:拒绝退货','0','0','1','1438757636','1437698629','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('timestamp','下单时间','int(10) NOT NULL','date','','下单时间','1','','0','0','1','1437698570','1437698570','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('user_id','用户id','int(10) NOT NULL','num','','用户id','1','','0','1','1','1437698325','1437698325','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ip','支付ip','varchar(255) NOT NULL','string','','支付ip','1','','0','0','1','1437698530','1437698530','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('total_fee','总费用','int(10) NOT NULL','num','','总费用','1','','0','0','1','1437698489','1437698489','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('product_field','商品','text NOT NULL','textarea','','商品信息','0','','0','0','1','1437698461','1437698461','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('unit_price','单价','int(10) NOT NULL','num','','单价','1','','0','0','1','1437899991','1437899991','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('pid','商品id','int(10) NOT NULL','num','','商品id','1','','0','0','1','1438263721','1438263721','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('settle_status','分销结算状态','int(50) NOT NULL','select','0','分销结算状态','1','0:未结算\r\n1:已经结算','0','0','1','1438777898','1438776104','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('by_from_openid','购买的上线openid','varchar(255) NOT NULL','string','','购买的上线openid','0','','0','0','1','1438778837','1438778837','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('receiver','收件人','varchar(255) NOT NULL','string','','收件人','1','','0','0','1','1438874669','1438874669','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('address','收件人地址','varchar(255) NOT NULL','string','','收件人地址','1','','0','0','1','1438874696','1438874696','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('phone','联系电弧','varchar(255) NOT NULL','string','','联系电话','1','','0','0','1','1438874719','1438874719','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;

CREATE TABLE IF NOT EXISTS `wp_shop_get_cash` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`openid`  varchar(255) NOT NULL  COMMENT 'openid',
`fee`  int(10) NOT NULL  COMMENT '取现金额（分）',
`ctime`  int(10) NOT NULL  COMMENT '申请取现时间',
`status`  int(50) NOT NULL  DEFAULT 0 COMMENT '状态',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_shop_get_cash` (`id`,`openid`,`fee`,`ctime`,`status`) VALUES ('1','osALzjvsweDff9UGcO13UWf2uYbw','100','1','0');
INSERT INTO `wp_shop_get_cash` (`id`,`openid`,`fee`,`ctime`,`status`) VALUES ('2','osALzjvsweDff9UGcO13UWf2uYbw','100','1','0');
INSERT INTO `wp_shop_get_cash` (`id`,`openid`,`fee`,`ctime`,`status`) VALUES ('3','osALzjvsweDff9UGcO13UWf2uYbw','1','1438927314','0');
INSERT INTO `wp_shop_get_cash` (`id`,`openid`,`fee`,`ctime`,`status`) VALUES ('4','osALzjvsweDff9UGcO13UWf2uYbw','1','1438927338','0');
INSERT INTO `wp_shop_get_cash` (`id`,`openid`,`fee`,`ctime`,`status`) VALUES ('5','osALzjvsweDff9UGcO13UWf2uYbw','100','1438927433','0');
INSERT INTO `wp_shop_get_cash` (`id`,`openid`,`fee`,`ctime`,`status`) VALUES ('6','osALzjvsweDff9UGcO13UWf2uYbw','100','1438927541','0');
INSERT INTO `wp_shop_get_cash` (`id`,`openid`,`fee`,`ctime`,`status`) VALUES ('7','osALzjvsweDff9UGcO13UWf2uYbw','200','1438928344','0');
INSERT INTO `wp_shop_get_cash` (`id`,`openid`,`fee`,`ctime`,`status`) VALUES ('8','osALzjvsweDff9UGcO13UWf2uYbw','200','1438928627','0');
INSERT INTO `wp_shop_get_cash` (`id`,`openid`,`fee`,`ctime`,`status`) VALUES ('9','osALzjvsweDff9UGcO13UWf2uYbw','200','1438928951','0');
INSERT INTO `wp_shop_get_cash` (`id`,`openid`,`fee`,`ctime`,`status`) VALUES ('10','osALzjvsweDff9UGcO13UWf2uYbw','200','1438929147','0');
INSERT INTO `wp_shop_get_cash` (`id`,`openid`,`fee`,`ctime`,`status`) VALUES ('11','osALzjvsweDff9UGcO13UWf2uYbw','100','1438929203','0');
INSERT INTO `wp_shop_get_cash` (`id`,`openid`,`fee`,`ctime`,`status`) VALUES ('12','osALzjvsweDff9UGcO13UWf2uYbw','100','1438929391','0');
INSERT INTO `wp_shop_get_cash` (`id`,`openid`,`fee`,`ctime`,`status`) VALUES ('13','osALzjvsweDff9UGcO13UWf2uYbw','200','1438929502','0');
INSERT INTO `wp_shop_get_cash` (`id`,`openid`,`fee`,`ctime`,`status`) VALUES ('14','osALzjvsweDff9UGcO13UWf2uYbw','200','1438929574','0');
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('shop_get_cash','用户取现','0','','1','{"1":["openid","fee","ctime","status"]}','1:基础','','','','','openid:openid\r\nfee:取现金额\r\nctime:申请取现时间\r\nstatus|get_name_by_status:状态','10','','','1438786223','1438790867','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('openid','openid','varchar(255) NOT NULL','string','','openid','1','','0','0','1','1438786259','1438786259','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('fee','取现金额（分）','int(10) NOT NULL','num','','取现金额','1','','0','0','1','1438786323','1438786323','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ctime','申请取现时间','int(10) NOT NULL','date','','取现时间','1','','0','0','1','1438786355','1438786355','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('status','状态','int(50) NOT NULL','select','0','状态','1','0:待取现\r\n1:成功取现\r\n2:被拒绝','0','0','1','1438787066','1438786444','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;

CREATE TABLE IF NOT EXISTS `wp_shop_product` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`img_1`  int(10) unsigned NOT NULL   COMMENT '商品图片1',
`img_2`  int(10) unsigned NOT NULL   COMMENT '商品图片2',
`title`  varchar(255) NOT NULL  COMMENT '商品名称',
`intro`  text NOT NULL  COMMENT '商品简介',
`mTime`  int(10) NOT NULL  COMMENT '修改时间',
`cover`  int(10) unsigned NOT NULL   COMMENT '商品封面图片',
`content`  text NOT NULL  COMMENT '商品详情',
`cTime`  int(10) unsigned NOT NULL   COMMENT '发布时间',
`token`  varchar(255) NOT NULL  COMMENT 'Token',
`param`  text NOT NULL  COMMENT '商品参数',
`ad_url`  varchar(255) NOT NULL  COMMENT '商品广告页面',
`buy_url`  varchar(255) NOT NULL  COMMENT '购买地址',
`cate_id_1`  int(10) unsigned NOT NULL   DEFAULT 0 COMMENT '商品一级分类',
`cate_id_2`  int(10) unsigned NOT NULL   DEFAULT 0 COMMENT '商品二级分类',
`market_price`  int(10) unsigned NOT NULL   DEFAULT 0 COMMENT '市场价',
`discount_price`  int(10) unsigned NOT NULL   DEFAULT 0 COMMENT '打折价',
`view_count`  int(10) unsigned NOT NULL   DEFAULT 0 COMMENT '浏览数',
`img_3`  int(10) unsigned NOT NULL   COMMENT '商品图片3',
`img_4`  int(10) unsigned NOT NULL   COMMENT '商品图片4',
`img_5`  int(10) unsigned NOT NULL   COMMENT '商品图片5',
`cate_id`  char(50) NOT NULL  COMMENT '商品分类',
`bug_count`  int(10) unsigned NOT NULL   DEFAULT 0 COMMENT '成交量',
`stock_price`  int(10) NOT NULL  COMMENT '进货价',
`stock`  int(10) NOT NULL  COMMENT '库存',
`back_deduct`  varchar(255) NOT NULL  COMMENT '现金返利',
`back_credit`  int(10) NOT NULL  DEFAULT 0 COMMENT '积分返利数',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_shop_product` (`id`,`title`,`intro`,`mTime`,`cover`,`content`,`cTime`,`token`,`param`,`ad_url`,`buy_url`,`cate_id_1`,`cate_id_2`,`market_price`,`discount_price`,`view_count`,`img_1`,`img_2`,`img_3`,`img_4`,`img_5`,`cate_id`,`bug_count`,`stock_price`,`back_credit`,`back_deduct`,`stock`) VALUES ('22','龙岩','一级龙岩，美容养颜，补血益气，抗辐射衰老','1437105646','369','','1437105646','gh_b6ff5c2aaf62','<p>蛋白质是维持棉衣技能最重要的营养素，为构成白血球和抗体的主要成分。<br/></p>','','','40','0','1','45','0','369','375','372','376','370','40','0','0','0','','0');
INSERT INTO `wp_shop_product` (`id`,`title`,`intro`,`mTime`,`cover`,`content`,`cTime`,`token`,`param`,`ad_url`,`buy_url`,`cate_id_1`,`cate_id_2`,`market_price`,`discount_price`,`view_count`,`img_1`,`img_2`,`img_3`,`img_4`,`img_5`,`cate_id`,`bug_count`,`stock_price`,`back_credit`,`back_deduct`,`stock`) VALUES ('23','水果','热销的水果','1437522596','369','','1437522596','gh_b6ff5c2aaf62','<p>参数2<br/></p>','','','40','0','100','50','0','369','375','372','0','0','40','0','0','0','','0');
INSERT INTO `wp_shop_product` (`id`,`title`,`intro`,`mTime`,`cover`,`content`,`cTime`,`token`,`param`,`ad_url`,`buy_url`,`cate_id_1`,`cate_id_2`,`market_price`,`discount_price`,`view_count`,`img_1`,`img_2`,`img_3`,`img_4`,`img_5`,`cate_id`,`bug_count`,`stock_price`,`back_credit`,`back_deduct`,`stock`) VALUES ('24','水果','测试','1437522641','375','','1437522641','gh_b6ff5c2aaf62','<p>热销2<br/></p>','','','40','0','200','50','0','376','370','368','377','367','40','0','0','0','','0');
INSERT INTO `wp_shop_product` (`id`,`title`,`intro`,`mTime`,`cover`,`content`,`cTime`,`token`,`param`,`ad_url`,`buy_url`,`cate_id_1`,`cate_id_2`,`market_price`,`discount_price`,`view_count`,`img_1`,`img_2`,`img_3`,`img_4`,`img_5`,`cate_id`,`bug_count`,`stock_price`,`back_credit`,`back_deduct`,`stock`) VALUES ('25','龙岩','','1438348464','372','','1437522676','gh_b6ff5c2aaf62','','','','0','0','2000','1000','0','368','370','376','372','375','40','0','500','0','','0');
INSERT INTO `wp_shop_product` (`id`,`title`,`intro`,`mTime`,`cover`,`content`,`cTime`,`token`,`param`,`ad_url`,`buy_url`,`cate_id_1`,`cate_id_2`,`market_price`,`discount_price`,`view_count`,`img_1`,`img_2`,`img_3`,`img_4`,`img_5`,`cate_id`,`bug_count`,`stock_price`,`back_credit`,`back_deduct`,`stock`) VALUES ('26','翡翠','翡翠中的翡翠','1438857789','367','','1437530832','gh_b6ff5c2aaf62','<p>    好吃    <br/></p>','','','40','0','20000','1500','0','370','368','367','375','375','40,43','0','900','0','','0');
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('shop_product','微商店商品','0','','1','{"1":["title","cover","intro","cate_id","market_price","discount_price","buy_url","ad_url","content","param","img_1","img_2","img_3","img_4","img_5","stock_price","first_deduct","second_deduct","third_deduct"]}','1:基础','','','','','id:商品ID\r\ncover|get_img_html:图片\r\ntitle:商品名称\r\ncate1_id|getCommonCategoryTitle:分类\r\nmarket_price:市场价\r\ndiscount_price:市场价\r\nview_count:浏览数\r\nid:操作:[EDIT]|编辑,[DELETE]|删除,config&pid=[id]|分销管理','10','title','','1396061373','1438870614','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('img_1','商品图片1','int(10) unsigned NOT NULL ','picture','','','1','','0','0','1','1398598870','1398598870','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('img_2','商品图片2','int(10) unsigned NOT NULL ','picture','','','1','','0','0','1','1398598904','1398598904','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('title','商品名称','varchar(255) NOT NULL','string','','','1','','0','1','1','1397520732','1396061859','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('intro','商品简介','text NOT NULL','textarea','','','1','','0','0','1','1397521079','1396061947','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('mTime','修改时间','int(10) NOT NULL','datetime','','','0','','0','0','1','1396624664','1396624664','','3','','regex','time','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('cover','商品封面图片','int(10) unsigned NOT NULL ','picture','','','1','','0','0','1','1397521134','1396062093','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('content','商品详情','text NOT NULL','editor','','','1','','0','0','1','1397521004','1396062146','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('cTime','发布时间','int(10) unsigned NOT NULL ','datetime','','','0','','0','0','1','1396624612','1396075102','','3','','regex','time','1','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','Token','varchar(255) NOT NULL','string','','','0','','0','0','1','1396602871','1396602859','','3','','regex','get_token','1','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('param','商品参数','text NOT NULL','editor','','','1','','0','0','1','1397521446','1397521446','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ad_url','商品广告页面','varchar(255) NOT NULL','string','','可为空，填写商品广告页面的地址','1','','0','0','1','1397521579','1397521579','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('buy_url','购买地址','varchar(255) NOT NULL','string','','用户点击购买按钮时跳转的地址，可以是淘宝等网店的购买地址','1','','0','0','1','1397524287','1397524287','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('cate_id_1','商品一级分类','int(10) unsigned NOT NULL ','num','0','','0','','0','0','1','1397524477','1397524433','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('cate_id_2','商品二级分类','int(10) unsigned NOT NULL ','num','0','','0','','0','0','1','1397524466','1397524466','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('market_price','市场价','int(10) unsigned NOT NULL ','num','0','','1','','0','0','1','1397525480','1397525480','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('discount_price','打折价','int(10) unsigned NOT NULL ','num','0','为空时只显示市场价','1','','0','0','1','1397525579','1397525579','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('view_count','浏览数','int(10) unsigned NOT NULL ','num','0','','0','','0','0','1','1397525660','1397525660','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('img_3','商品图片3','int(10) unsigned NOT NULL ','picture','','','1','','0','0','1','1398598938','1398598938','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('img_4','商品图片4','int(10) unsigned NOT NULL ','picture','','','1','','0','0','1','1398598960','1398598960','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('img_5','商品图片5','int(10) unsigned NOT NULL ','picture','','','1','','0','0','1','1398598981','1398598981','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('cate_id','商品分类','char(50) NOT NULL','cascade','','','1','type=db&table=common_category&module=shop_category','0','0','1','1398693036','1398599395','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('bug_count','成交量','int(10) unsigned NOT NULL ','num','0','','0','','0','0','1','1399002900','1399002900','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('stock_price','进货价','int(10) NOT NULL','num','','进货价(单位:分)','1','','0','0','1','1438337222','1438337222','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('stock','库存','int(10) NOT NULL','num','','库存','1','','0','0','1','1438874027','1438874027','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('back_deduct','现金返利','varchar(255) NOT NULL','string','','现金返利','1','','0','0','1','1438873962','1438873962','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('back_credit','积分返利数','int(10) NOT NULL','num','0','积分返利数','1','','0','0','1','1438873902','1438873902','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;

CREATE TABLE IF NOT EXISTS `wp_shop_product_dis` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`pid`  int(10) NOT NULL  COMMENT '商品id',
`partner_deduct`  varchar(255) NOT NULL  COMMENT '合伙人总提成',
`manager_deduct`  varchar(255) NOT NULL  COMMENT '经理提成',
`seller_deduct`  varchar(255) NOT NULL  COMMENT '销售员提成',
`partner_credict`  varchar(255) NOT NULL  COMMENT '合伙人积分',
`manager_credit`  varchar(255) NOT NULL  COMMENT '经理积分',
`seller_credit`  int(10) NOT NULL  COMMENT '销售员积分',
`token`  varchar(255) NOT NULL  COMMENT 'token',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_shop_product_dis` (`id`,`pid`,`partner_deduct`,`manager_deduct`,`seller_deduct`,`partner_credict`,`manager_credit`,`seller_credit`,`token`) VALUES ('1','24','0.2','','0.5','','0','0','gh_b6ff5c2aaf62');
INSERT INTO `wp_shop_product_dis` (`id`,`pid`,`partner_deduct`,`manager_deduct`,`seller_deduct`,`partner_credict`,`manager_credit`,`seller_credit`,`token`) VALUES ('2','25','0.5','','0.2','','0','0','gh_b6ff5c2aaf62');
INSERT INTO `wp_shop_product_dis` (`id`,`pid`,`partner_deduct`,`manager_deduct`,`seller_deduct`,`partner_credict`,`manager_credit`,`seller_credit`,`token`) VALUES ('3','26','0.2','','0.5','','0','0','gh_b6ff5c2aaf62');
INSERT INTO `wp_shop_product_dis` (`id`,`pid`,`partner_deduct`,`manager_deduct`,`seller_deduct`,`partner_credict`,`manager_credit`,`seller_credit`,`token`) VALUES ('4','0','0.2','','0.5','','0','0','gh_b6ff5c2aaf62');
INSERT INTO `wp_shop_product_dis` (`id`,`pid`,`partner_deduct`,`manager_deduct`,`seller_deduct`,`partner_credict`,`manager_credit`,`seller_credit`,`token`) VALUES ('13','26','0.2','0.3','0.5','','0','0','gh_b6ff5c2aaf62');
INSERT INTO `wp_shop_product_dis` (`id`,`pid`,`partner_deduct`,`manager_deduct`,`seller_deduct`,`partner_credict`,`manager_credit`,`seller_credit`,`token`) VALUES ('12','25','0.5','0.3','0.2','','0','0','gh_b6ff5c2aaf62');
INSERT INTO `wp_shop_product_dis` (`id`,`pid`,`partner_deduct`,`manager_deduct`,`seller_deduct`,`partner_credict`,`manager_credit`,`seller_credit`,`token`) VALUES ('11','24','0.2','0.3','0.5','','0','0','gh_b6ff5c2aaf62');
INSERT INTO `wp_shop_product_dis` (`id`,`pid`,`partner_deduct`,`manager_deduct`,`seller_deduct`,`partner_credict`,`manager_credit`,`seller_credit`,`token`) VALUES ('8','25','0.5','','0.2','','0','0','gh_b6ff5c2aaf62');
INSERT INTO `wp_shop_product_dis` (`id`,`pid`,`partner_deduct`,`manager_deduct`,`seller_deduct`,`partner_credict`,`manager_credit`,`seller_credit`,`token`) VALUES ('9','23','0.2','0.3','0.5','','0','0','gh_b6ff5c2aaf62');
INSERT INTO `wp_shop_product_dis` (`id`,`pid`,`partner_deduct`,`manager_deduct`,`seller_deduct`,`partner_credict`,`manager_credit`,`seller_credit`,`token`) VALUES ('10','22','0.2','0.3','0.5','','0','0','gh_b6ff5c2aaf62');
INSERT INTO `wp_shop_product_dis` (`id`,`pid`,`partner_deduct`,`manager_deduct`,`seller_deduct`,`partner_credict`,`manager_credit`,`seller_credit`,`token`) VALUES ('14','22','0.3','0.2','0.5','','0','0','gh_b6ff5c2aaf62');
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('shop_product_dis','商品分销','0','','1','','1:基础','','','','','','10','','','1438868331','1438868331','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('pid','商品id','int(10) NOT NULL','num','','商品id','1','','0','0','1','1438868393','1438868393','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('partner_deduct','合伙人总提成','varchar(255) NOT NULL','string','','合伙人总提成','1','','0','0','1','1438868485','1438868485','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('manager_deduct','经理提成','varchar(255) NOT NULL','string','','经理提成','1','','0','0','1','1438871498','1438868675','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('seller_deduct','销售员提成','varchar(255) NOT NULL','string','','销售员提成','1','','0','0','1','1438868722','1438868722','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('partner_credict','合伙人积分','varchar(255) NOT NULL','num','','合伙人积分','1','','0','0','1','1438868979','1438868844','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('manager_credit','经理积分','varchar(255) NOT NULL','num','','经理积分','1','','0','0','1','1438868968','1438868905','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('seller_credit','销售员积分','int(10) NOT NULL','num','','销售员积分','1','','0','0','1','1438868954','1438868954','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','token','varchar(255) NOT NULL','string','','token','1','','0','0','1','1438869725','1438869725','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;

CREATE TABLE IF NOT EXISTS `wp_shop_return_order` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`oid`  int(10) NOT NULL  COMMENT '订单id',
`reason`  int(10) NOT NULL  COMMENT '退货理由',
`fee`  int(10) NOT NULL  COMMENT '费用',
`token`  varchar(255) NOT NULL  COMMENT 'token',
`status`  int(10) NOT NULL  DEFAULT 2 COMMENT '退单状态',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_shop_return_order` (`id`,`oid`,`reason`,`fee`,`token`,`status`) VALUES ('4','17','商品很好','45','gh_b6ff5c2aaf62','2');
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('shop_return_order','退货表','0','','1','{"1":["oid","reason","fee","token","status"]}','1:基础','','','','','id:退货单id\r\noid:订货单id\r\nreason:退货理由\r\nfee:退费\r\nstatus|get_name_by_status:状态\r\nid:操作:agreeReturn&id=[id]|同意退款','10','','','1438876058','1438938374','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('oid','订单id','int(10) NOT NULL','num','','订单id','1','','0','0','1','1438876091','1438876091','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('reason','退货理由','int(10) NOT NULL','string','','退货理由','1','','0','0','1','1438935578','1438876128','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('fee','费用','int(10) NOT NULL','num','','费用（单位：分）','1','','0','0','1','1438876188','1438876188','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','token','varchar(255) NOT NULL','string','','token','1','','0','0','1','1438876203','1438876203','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('status','退单状态','int(10) NOT NULL','select','2','退单状态','1','1:退款成功\r\n2:待退款\r\n3:退款失败','0','0','1','1438876302','1438876287','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;

CREATE TABLE IF NOT EXISTS `wp__shop_settled` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('shop_settled','已经结算订单','1','','1','','1:基础','','','','','','10','','','1438764550','1438764550','1','MyISAM');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;

CREATE TABLE IF NOT EXISTS `wp_shop_user` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`ctime`  int(10) NOT NULL  COMMENT '创建时间',
`nickname`  varchar(255) NOT NULL  COMMENT '昵称',
`openid`  varchar(255) NOT NULL  COMMENT '微信用户的openid',
`token`  varchar(255) NOT NULL  COMMENT 'token',
`address`  varchar(255) NOT NULL  COMMENT '地址',
`phone`  varchar(255) NOT NULL  COMMENT '电话',
`remain_money`  int(10) NOT NULL  COMMENT '账户余额',
`user_cat`  char(10) NOT NULL  DEFAULT 999 COMMENT '用户类型',
`credit`  int(10) NOT NULL  COMMENT '积分',
`profit_percentage`  varchar(255) NOT NULL  COMMENT '合伙人的利润提成百分比（以小数形式表示），非合伙人类别，填了也没用',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_shop_user` (`id`,`openid`,`nickname`,`phone`,`address`,`ctime`,`token`,`remain_money`,`user_cat`,`credit`,`profit_percentage`) VALUES ('1','osALzjvsweDff9UGcO13UWf2uYbw','黎明','13943152429','云南省昆明市','1438349700','gh_b6ff5c2aaf62','100','0','0','0.7');
INSERT INTO `wp_shop_user` (`id`,`openid`,`nickname`,`phone`,`address`,`ctime`,`token`,`remain_money`,`user_cat`,`credit`,`profit_percentage`) VALUES ('2','-1','小芬','1102233344','安徽省','2015','gh_b6ff5c2aaf62','0','999','0','');
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('shop_user','微商用户','0','','1','{"1":["ctime","nickname","openid","token","address","phone","remain_money","user_cat"]}','1:基础','','','','','id:会员ID\r\nnickname:昵称\r\nopenid:openId\r\naddress:住址\r\nphone:电话\r\nuser_cat|get_name_by_status:用户分类\r\nremain_money:余额\r\nid:操作:[EDIT]|编辑,[DELETE]|删除','10','openid,nickname','','1437701471','1438747930','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('ctime','创建时间','int(10) NOT NULL','datetime','','','1','','0','0','1','1437701869','1437701869','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('nickname','昵称','varchar(255) NOT NULL','string','','昵称','1','','0','0','1','1437701780','1437701780','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('openid','微信用户的openid','varchar(255) NOT NULL','string','','微信用户openid','1','','0','0','1','1437701744','1437701744','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','token','varchar(255) NOT NULL','string','','','1','','0','0','1','1437701886','1437701886','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('address','地址','varchar(255) NOT NULL','string','','地址','1','','0','0','1','1437701843','1437701843','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('phone','电话','varchar(255) NOT NULL','string','','电话','1','','0','0','1','1437701814','1437701814','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('remain_money','账户余额','int(10) NOT NULL','num','','余额','1','','0','0','1','1438338265','1438338265','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('user_cat','用户类型','char(10) NOT NULL','select','999','用户类型','1','0:合伙人\r\n1:总代理\r\n2:分销商\r\n999:普通用户','0','0','1','1438747812','1438747812','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('credit','积分','int(10) NOT NULL','num','','积分','1','','0','0','1','1438874125','1438874125','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('profit_percentage','合伙人的利润提成百分比（以小数形式表示），非合伙人类别，填了也没用','varchar(255) NOT NULL','string','','合伙人的利润提成百分比（以小数形式表示），非合伙人类别，填了也没用','1','','0','0','1','1438875461','1438875461','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;