CREATE TABLE IF NOT EXISTS `wp_qr_code` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
`qr_code`  varchar(255) NOT NULL  COMMENT '二维码',
`addon`  varchar(255) NOT NULL  COMMENT '二维码所属插件',
`aim_id`  int(10) unsigned NOT NULL   COMMENT '插件表里的ID值',
`cTime`  int(10) NOT NULL  COMMENT '创建时间',
`token`  varchar(255) NOT NULL  COMMENT 'Token',
`action_name`  char(30) NOT NULL  DEFAULT 'QR_SCENE' COMMENT '二维码类型',
`extra_text`  text NULL   COMMENT '文本扩展',
`extra_int`  int(10) NULL   COMMENT '数字扩展',
`request_count`  int(10) NOT NULL  DEFAULT 0 COMMENT '请求数',
`scene_id`  int(10) NOT NULL  DEFAULT 0 COMMENT '场景ID',
PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci CHECKSUM=0 ROW_FORMAT=DYNAMIC DELAY_KEY_WRITE=0;
INSERT INTO `wp_model` (`name`,`title`,`extend`,`relation`,`need_pk`,`field_sort`,`field_group`,`attribute_list`,`template_list`,`template_add`,`template_edit`,`list_grid`,`list_row`,`search_key`,`search_list`,`create_time`,`update_time`,`status`,`engine_type`) VALUES ('qr_code','二维码表','0','','1','{"1":["qr_code","addon","aim_id","cTime","extra_text","extra_int","scene_id","action_name"]}','1:基础','','','','','scene_id:事件KEY值\r\nqr_code|get_code_img:二维码\r\naction_name|get_name_by_status: 	二维码类型\r\naddon:所属插件\r\naim_id:插件数据ID\r\ncTime|time_format:增加时间\r\nrequest_count|intval:请求数\r\nid:操作:[EDIT]|编辑,[DELETE]|删除','10','qr_code','','1388815871','1406130247','1','MyISAM');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('qr_code','二维码','varchar(255) NOT NULL','string','','','1','','0','1','1','1406127577','1388815953','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('addon','二维码所属插件','varchar(255) NOT NULL','string','','','1','','0','1','1','1406127594','1388816207','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('aim_id','插件表里的ID值','int(10) unsigned NOT NULL ','num','','','1','','0','1','1','1388816287','1388816287','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('cTime','创建时间','int(10) NOT NULL','datetime','','','1','','0','0','1','1388816392','1388816392','','1','','regex','time','1','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('token','Token','varchar(255) NOT NULL','string','','','0','','0','0','1','1391399528','1391399528','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('action_name','二维码类型','char(30) NOT NULL','select','QR_SCENE','QR_SCENE为临时,QR_LIMIT_SCENE为永久 ','1','QR_SCENE:临时二维码\r\nQR_LIMIT_SCENE:永久二维码','0','0','1','1406130162','1393919686','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('extra_text','文本扩展','text NULL ','textarea','','','1','','0','0','1','1393919736','1393919736','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('extra_int','数字扩展','int(10) NULL ','num','','','1','','0','0','1','1393919798','1393919798','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('request_count','请求数','int(10) NOT NULL','num','0','用户回复的次数','0','','0','0','1','1402547625','1401938983','','3','','regex','','3','function');
INSERT INTO `wp_attribute` (`name`,`title`,`field`,`type`,`value`,`remark`,`is_show`,`extra`,`model_id`,`is_must`,`status`,`update_time`,`create_time`,`validate_rule`,`validate_time`,`error_info`,`validate_type`,`auto_rule`,`auto_time`,`auto_type`) VALUES ('scene_id','场景ID','int(10) NOT NULL','num','0','','1','','0','0','1','1406127542','1406127542','','3','','regex','','3','function');
UPDATE `wp_attribute` SET model_id= (SELECT MAX(id) FROM `wp_model`) WHERE model_id=0;